In [2]:
import warnings
warnings.filterwarnings('ignore') 

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [10]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9407407407407408

In [11]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.43333333333333335

In [12]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [22]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [28]:
scores_logistic

[0.9282136894824707, 0.9432387312186978, 0.9165275459098498]

In [29]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [30]:
scores_rf

[0.9282136894824707, 0.9432387312186978, 0.9165275459098498]

In [40]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target,cv=3)

array([0.92153589, 0.94156928, 0.91652755])

In [41]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92222222, 0.90555556, 0.94986072, 0.95821727, 0.89693593])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.925     , 0.90833333, 0.95264624, 0.95543175, 0.9275766 ])