In [30]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df= pd.read_csv('./datasets_for_tuts/carprices.csv')
df


Car_Model  Mileage  Sell_Price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez Benz C class    67000       22000    6
10  Mercedez Benz C class    83000       20000    7
11  Mercedez Benz C class    79000       21000    7
12  Mercedez Benz C class    59000       33000    5

In [3]:
dummies=pd.get_dummies(df.Car_Model)
dummies

Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [4]:
merged = pd.concat([df,dummies],axis='columns')
merged

Car_Model  Mileage  Sell_Price  Age  Audi A5  BMW X5  \
0                  BMW X5    69000       18000    6    False    True   
1                  BMW X5    35000       34000    3    False    True   
2                  BMW X5    57000       26100    5    False    True   
3                  BMW X5    22500       40000    2    False    True   
4                  BMW X5    46000       31500    4    False    True   
5                 Audi A5    59000       29400    5     True   False   
6                 Audi A5    52000       32000    5     True   False   
7                 Audi A5    72000       19300    6     True   False   
8                 Audi A5    91000       12000    8     True   False   
9   Mercedez Benz C class    67000       22000    6    False   False   
10  Mercedez Benz C class    83000       20000    7    False   False   
11  Mercedez Benz C class    79000       21000    7    False   False   
12  Mercedez Benz C class    59000       33000    5    False   False   

    Mercedez Benz C class  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
5                   False  
6                   False  
7                   False  
8                   False  
9                    True  
10                   True  
11                   True  
12                   True

In [5]:
final = merged.drop(['Car_Model','Audi A5'],axis='columns')
final

Mileage  Sell_Price  Age  BMW X5  Mercedez Benz C class
0     69000       18000    6    True                  False
1     35000       34000    3    True                  False
2     57000       26100    5    True                  False
3     22500       40000    2    True                  False
4     46000       31500    4    True                  False
5     59000       29400    5   False                  False
6     52000       32000    5   False                  False
7     72000       19300    6   False                  False
8     91000       12000    8   False                  False
9     67000       22000    6   False                   True
10    83000       20000    7   False                   True
11    79000       21000    7   False                   True
12    59000       33000    5   False                   True

In [6]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [7]:
X = final.drop(['Sell_Price'],axis='columns')
X

Mileage  Age  BMW X5  Mercedez Benz C class
0     69000    6    True                  False
1     35000    3    True                  False
2     57000    5    True                  False
3     22500    2    True                  False
4     46000    4    True                  False
5     59000    5   False                  False
6     52000    5   False                  False
7     72000    6   False                  False
8     91000    8   False                  False
9     67000    6   False                   True
10    83000    7   False                   True
11    79000    7   False                   True
12    59000    5   False                   True

In [8]:
y= final.Sell_Price
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Price, dtype: int64

In [9]:
model.fit(X,y)

LinearRegression()

In [10]:
model.predict([[10000,3,0,0]])

array([48824.50340456])

In [11]:
model.score(X,y)

0.9417050937281082

In [12]:
df

Car_Model  Mileage  Sell_Price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez Benz C class    67000       22000    6
10  Mercedez Benz C class    83000       20000    7
11  Mercedez Benz C class    79000       21000    7
12  Mercedez Benz C class    59000       33000    5

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [14]:
dfle = df
dfle.Car_Model = le.fit_transform(dfle.Car_Model)

In [33]:
dfle

Car_Model  Mileage  Sell_Price  Age
0           1    69000       18000    6
1           1    35000       34000    3
2           1    57000       26100    5
3           1    22500       40000    2
4           1    46000       31500    4
5           0    59000       29400    5
6           0    52000       32000    5
7           0    72000       19300    6
8           0    91000       12000    8
9           2    67000       22000    6
10          2    83000       20000    7
11          2    79000       21000    7
12          2    59000       33000    5

In [56]:
from sklearn.preprocessing import StandardScaler
dfle2 = StandardScaler()
dfle2.fit(dfle)

StandardScaler()

In [67]:
dfle2

StandardScaler()

In [41]:
X = dfle[2['Car_Model']].values
X
#,'Mileage','Age'

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]])

In [42]:
y = dfle.Sell_Price
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell_Price, dtype: int64

In [58]:
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder()

In [59]:
df

Car_Model  Mileage  Sell_Price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez Benz C class    67000       22000    6
10  Mercedez Benz C class    83000       20000    7
11  Mercedez Benz C class    79000       21000    7
12  Mercedez Benz C class    59000       33000    5

In [60]:
X = ohe.fit_transform(X)
X

<13x138 sparse matrix of type '<class 'numpy.float64'>'
	with 897 stored elements in Compressed Sparse Row format>

In [61]:
dfle

Car_Model  Mileage  Sell_Price  Age
0           1    69000       18000    6
1           1    35000       34000    3
2           1    57000       26100    5
3           1    22500       40000    2
4           1    46000       31500    4
5           0    59000       29400    5
6           0    52000       32000    5
7           0    72000       19300    6
8           0    91000       12000    8
9           2    67000       22000    6
10          2    83000       20000    7
11          2    79000       21000    7
12          2    59000       33000    5

In [62]:
#X = X[:,1:]
#X

In [63]:
model.fit(X,y)

LinearRegression()

In [40]:
model.predict([[1,0,10000,3]])

ValueError: X has 4 features, but LinearRegression is expecting 35 features as input.

In [53]:
X[4]

array([0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0.])