In [2]:
pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df=pd.read_csv("./linear_regression/prices.csv")
df

reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.prices)
reg.predict([[3400]])

C:\Users\narve\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6422.94520548])

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [9]:
with open('model_pickle','rb') as f:
    model= pickle.load(f)

In [12]:
model.predict([[5000]])

C:\Users\narve\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8595.54794521])

In [14]:
import joblib

In [15]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [16]:
mj=joblib.load('model_joblib')
mj.predict([[5000]])

C:\Users\narve\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8595.54794521])

In [18]:
mj.coef_

array([1.35787671])

In [19]:
mj.intercept_

1806.1643835616433